name: Test

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build: 
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2

      - name: Pull the change from server
        env:
          USERNAME: ${{ secrets.USERNAME }}
          TOKEN: ${{ secrets.TOKEN }}
        run: | 
          git pull origin master --rebase
          echo $USERNAME
          echo $TOKEN
